package com.jdjz.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import android.net.Uri;
import android.os.Parcel;
import android.os.Parcelable;
import android.text.TextUtils;

import com.jdjz.common.ParcelUtils;
import com.jdjz.model.UserInfo;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;


/**
 * Entity mapped to table FRIEND.
 */
@Entity
public class Friend  {
    @Id
    private String userId;
    private String name;
    private String portraitUri;
    private String displayName;
    private String region;
    private String phoneNumber;
    private String status;
    private Long timestamp;
    private String letters;
    private String nameSpelling;
    private String displayNameSpelling;
    @Generated(hash = 727525608)
    public Friend(String userId, String name, String portraitUri, String displayName, String region,
            String phoneNumber, String status, Long timestamp, String letters, String nameSpelling,
            String displayNameSpelling) {
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.region = region;
        this.phoneNumber = phoneNumber;
        this.status = status;
        this.timestamp = timestamp;
        this.letters = letters;
        this.nameSpelling = nameSpelling;
        this.displayNameSpelling = displayNameSpelling;
    }



    public Friend(String userId, String name, String portraitUri) {
        this.userId = userId;
        this.name = name;
        this. portraitUri = portraitUri;
    }

//    public Friend(String userId, String name, String portraitUri, String displayName, String region, String phoneNumber, String status, Long timestamp, String nameSpelling, String displayNameSpelling, String letters) {
//        this.userId = userId;
//        this.name = name;
//        this.portraitUri = portraitUri;
//        this.displayName = displayName;
//        this.region = region;
//        this.phoneNumber = phoneNumber;
//        this.status = status;
//        this.timestamp = timestamp;
//        this.nameSpelling = nameSpelling;
//        this.displayNameSpelling = displayNameSpelling;
//        this.letters = letters;
//    }

    public Friend(String userId, String name, String portraitUri, String displayName, String region, String phoneNumber, String status, Long timestamp, String nameSpelling, String displayNameSpelling) {
        // super(userId, name, portraitUri);
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.region = region;
        this.phoneNumber = phoneNumber;
        this.status = status;
        this.timestamp = timestamp;
        this.nameSpelling = nameSpelling;
        this.displayNameSpelling = displayNameSpelling;
    }

    public Friend(String userId, String name, String portraitUri, String displayName, String region, String phoneNumber, String status, Long timestamp) {
        //super(userId, name, portraitUri);
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.region = region;
        this.phoneNumber = phoneNumber;
        this.status = status;
        this.timestamp = timestamp;
    }

    public Friend(String userId, String name, String portraitUri, String displayName, String status, Long timestamp) {
        //super(userId, name, portraitUri);
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.status = status;
        this.timestamp = timestamp;
    }

    public Friend(String userId, String name, String portraitUri, String phoneNumber, String displayName) {
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.phoneNumber = phoneNumber;
        this.displayName = displayName;
    }

    public Friend(String userId, String name, String portraitUri, String displayName) {
        //super(userId, name, portraitUri);
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
    }

    @Generated(hash = 287143722)
    public Friend() {
    }
    public String getUserId() {
        return this.userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getRegion() {
        return this.region;
    }
    public void setRegion(String region) {
        this.region = region;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getStatus() {
        return this.status;
    }
    public void setStatus(String status) {
        this.status = status;
    }
    public Long getTimestamp() {
        return this.timestamp;
    }
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }
    public String getLetters() {
        return this.letters;
    }
    public void setLetters(String letters) {
        this.letters = letters;
    }
    public String getNameSpelling() {
        return this.nameSpelling;
    }
    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }
    public String getDisplayNameSpelling() {
        return this.displayNameSpelling;
    }
    public void setDisplayNameSpelling(String displayNameSpelling) {
        this.displayNameSpelling = displayNameSpelling;
    }
    public String getPortraitUri() {
        return this.portraitUri;
    }
    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

}
